### ISSUE TITLE
Dictionary Or Tuple 

### ISSUE THREAD

**Issue by elbadawyy** [elbadawyy/Hash-POS#12]
I think we need to use dictionaries instead of tuples. It makes the code more readable, writable and easier to remember.

**Comment by sleek-geek** [comment]
Tuples are different than dictionaries by the very definitions of what they do and used for.

Dictionaries are used to associate one value to another. That's not what we need here. We just need a simple constant set of DB fields and another set of input values, besides turning them into dictionaries would force us to change the format to match the query's. Read addEntry method and you'll know what I mean.

 What do u mean by "more readable writable and easier to remember"? I don't think readability is a problem here the code looks readable as is. What I can't imagine​, however,  is how dictionaries will be useful here. If you have a point  , please make it more clear, a sample code would be helpful. If you don't, then close the issue.

**Comment by elbadawyy** [comment]
Sure I know it 'll force us to change the format to match the query's. Not a big deal we at the start of the project.

Example of readability I meant that
item['name'] = "pen"  definitely more readable and meaningful than item['1']="pen"  which we use now.
by seen this item['name'] I knew I assign name of the item and don't have to go to check the the index of name every time I need to use it.

**Comment by sleek-geek** [comment]
Closed due to a discussion that led to the inevitable fact that tuples are better than dictionaries in this case.
